# Exercise 1

Create a NumPy array of 15 elements and reshape it into a 3x5 matrix.

In [33]:
import numpy as np

X = np.random.randn(15)
X

array([ 0.54897546, -0.20292836, -0.06292701, -0.61022866, -0.74005151,
       -0.21037164, -0.45725767, -0.60489667, -0.87360608, -1.07769428,
        0.43117354, -0.47516854,  1.03369205, -0.04950406, -1.16545688])

In [34]:
X.shape

(15,)

In [36]:
Y = X.reshape(3, 5)
Y

array([[ 0.54897546, -0.20292836, -0.06292701, -0.61022866, -0.74005151],
       [-0.21037164, -0.45725767, -0.60489667, -0.87360608, -1.07769428],
       [ 0.43117354, -0.47516854,  1.03369205, -0.04950406, -1.16545688]])

In [37]:
Y.shape

(3, 5)

# Exercise 2

Replace all odd numbers in a NumPy array of 0–9 with -2.

In [38]:
X = np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
X % 2 == 1

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [41]:
X[X % 2 == 1] = -2

In [42]:
X

array([ 0, -2,  2, -2,  4, -2,  6, -2,  8, -2])

# Exercise 3

Extract all elements greater than 35 from a 5x5 matrix of values from 25 to 49.

In [44]:
X = np.arange(25, 50).reshape(5, 5)
X

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [45]:
X[X > 35]

array([36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

# Exercise 4 

Generate a 1D array of 10 elements and reverse it using slicing.

In [46]:
X = np.random.randn(10)
X

array([-0.47832664, -0.93664969, -0.42488427,  0.28871325,  0.34551224,
       -0.8927408 , -0.62697234, -0.58508452,  1.17913553,  1.1907129 ])

In [49]:
X[::-1]

array([ 1.1907129 ,  1.17913553, -0.58508452, -0.62697234, -0.8927408 ,
        0.34551224,  0.28871325, -0.42488427, -0.93664969, -0.47832664])

# Exercise 5 

Create a 3x5 array, and extract the third column.

In [50]:
X = np.random.randint(1, 100, size=15).reshape(3, 5)
X

array([[64, 92, 74, 63, 47],
       [69, 11, 64, 23, 28],
       [ 5, 22, 35, 96, 89]])

In [51]:
X[:, 2]

array([74, 64, 35])

# Exercise 6 

Create a 1D array with 10 values and compute the exponential of each of the values.

In [52]:
X = np.random.randn(10)
X

array([ 0.3911726 , -0.6695494 ,  0.53515113, -0.22016923,  2.54398034,
       -0.79502535,  0.76697839,  0.57270904,  0.98771211, -1.14675955])

In [53]:
np.exp(X)

array([ 1.47871372,  0.5119392 ,  1.70770632,  0.802383  , 12.73024095,
        0.45156979,  2.15325014,  1.77306386,  2.68508427,  0.31766448])

# Exercise 7

Create the 3x5 array and swap the first and last rows.

In [54]:
X = np.random.randn(15).reshape(3, 5)
X

array([[-1.58455492,  1.28409161, -1.12971152, -3.64119176, -0.93903906],
       [-0.70711971,  0.46957486, -2.06030732, -0.60596827, -2.47878065],
       [-0.08574168, -1.30576909,  1.40226976,  1.57233499, -0.45898441]])

In [55]:
X[[0, -1]] = X[[-1, 0]]
X

array([[-0.08574168, -1.30576909,  1.40226976,  1.57233499, -0.45898441],
       [-0.70711971,  0.46957486, -2.06030732, -0.60596827, -2.47878065],
       [-1.58455492,  1.28409161, -1.12971152, -3.64119176, -0.93903906]])

# Exercise 8 

Create two 1D arrays and perform arithmetic operations with them.

In [56]:
X = np.random.randint(1, 100, size=10)
Y = np.random.randint(1, 100, size=10)

X

array([ 3, 48, 70,  1, 90, 41, 80, 90, 38, 88])

In [57]:
Y

array([76, 16, 17, 82, 63, 91, 13, 37, 27, 78])

In [58]:
X + Y

array([ 79,  64,  87,  83, 153, 132,  93, 127,  65, 166])

In [59]:
X - Y

array([-73,  32,  53, -81,  27, -50,  67,  53,  11,  10])

In [60]:
X * Y

array([ 228,  768, 1190,   82, 5670, 3731, 1040, 3330, 1026, 6864])

In [61]:
X / Y

array([0.03947368, 3.        , 4.11764706, 0.01219512, 1.42857143,
       0.45054945, 6.15384615, 2.43243243, 1.40740741, 1.12820513])

In [62]:
X = np.random.randint(1, 100, size=5)
Y = np.random.randint(1, 100, size=7)

X

array([60, 18, 13, 89, 63])

In [63]:
Y

array([35,  8, 23, 56, 90, 59, 16])

In [64]:
X + Y

ValueError: operands could not be broadcast together with shapes (5,) (7,) 

In [65]:
X -  Y

ValueError: operands could not be broadcast together with shapes (5,) (7,) 