In [4]:
import numpy as np

X = np.array([1, 2, 3, 4, 5])
X

array([1, 2, 3, 4, 5])

In [5]:
X.shape

(5,)

In [6]:
Y = np.array([[1, 2, 3], [4, 5, 6]])
Y

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
Y.shape

(2, 3)

In [8]:
3*X

array([ 3,  6,  9, 12, 15])

In [9]:
X**2

array([ 1,  4,  9, 16, 25])

In [10]:
np.square(X)

array([ 1,  4,  9, 16, 25])

In [12]:
np.zeros((2, 3)).dtype

dtype('float64')

In [14]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
X

array([1, 2, 3, 4, 5])

In [16]:
%%time
import math
result = [math.sqrt(abs(x)) for x in X]

CPU times: user 7 µs, sys: 8 µs, total: 15 µs
Wall time: 16.9 µs


In [17]:
%%time
result = np.sqrt(np.abs(X))

CPU times: user 393 µs, sys: 0 ns, total: 393 µs
Wall time: 7.29 ms


In [18]:
16.9/7.29

2.3182441700960217